name: Build and Deploy to Cloud Function

on:
  push:
    paths:
      - backend/**
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: populate-trends

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
          service_account_key: ${{ secrets.GCLOUD_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}
      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud functions deploy "$SERVICE_NAME" \
            --trigger-topic tj-trends \
            --runtime go111 \
            --entry-point GetLatestTrends \
            --source backend
