name: Build and Deploy to Cloud Function

on:
  push:
    paths:
      - backend/**
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: populate-trends

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

    # Setup gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
    # Deploy image to Cloud Run
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Deploy
      run: |-
        gcloud functions deploy "$SERVICE_NAME" \
          --trigger-topic tj-trends \
          --runtime go113 \
          --entry-point GetLatestTrends \
          --source backend
