name: Build and Deploy to Cloud Function

on:
  workflow_dispatch:
    branches: [main]
  push:
    paths:
      - backend/**
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: populate-trends
  ENTRY_POINT: GetLatestTrends
  TRIGGER_RESOURCE: tj-trends

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

    # Setup gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
    # check env
    - name: 'check env'
      run: env
    # Deploy image to Cloud Run
    - name: 'deploy function'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: "${{ env.SERVICE_NAME }}"
        runtime: 'go116'
        entry_point: "$env.ENTRY_POINT"
        event_trigger_type: 'topic'
        event_trigger_resource: "${{ env.TRIGGER_RESOURCE }}"
        source_dir: 'backend'