name: Netlify Deploy

on:
  workflow_dispatch:
    branches: [main]
  push:
    paths:
      - frontend/**
    branches:
      - main
  schedule:
    - cron: '5 0-3,12-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

      # Setup gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
      - name: npm install, build
        env:
          NETLIFY_ACCESS_TOKEN: ${{secrets.NETLIFY_ACCESS_TOKEN}}
          NETLIFY_SITE: ${{secrets.NETLIFY_SITE}}
          STRAVA_ACCESS_TOKEN: ${{secrets.STRAVA_ACCESS_TOKEN}}
          STRAVA_CLIENT_ID: ${{secrets.STRAVA_CLIENT_ID}}
          STRAVA_CLIENT_SECRET: ${{secrets.STRAVA_CLIENT_SECRET}}
          STRAVA_EXPIRY: ${{secrets.STRAVA_EXPIRY}}
          STRAVA_REFRESH_TOKEN: ${{secrets.STRAVA_REFRESH_TOKEN}}
          MAPTILER_KEY: ${{secrets.MAPTILER_KEY}}
          PIRATEWEATHER_KEY: ${{secrets.PIRATEWEATHER_KEY}}
        run: |
          cd frontend
          npm ci
          npm run build
          echo 'Done'
          ls -la _site/images
      - name: Deploy to Netlify
        uses: 'netlify/actions/cli@master'
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_ACCESS_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE}}
        with:
          args: 'deploy -p --dir=frontend/_site'
